import { CatDetail } from "./interfaces/cat-detail.interface";
import { CatBreedInfo } from "./interfaces/cat-info.interface";

export const mockCatBreedInfo: CatBreedInfo = {
    breeds: [
      {
        weight: { imperial: 'string', metric: 'string' },
        id: 'string',
        name: 'string',
        cfa_url: '',
        vetstreet_url: '',
        vcahospitals_url: '',
        temperament: 'string',
        origin: 'string',
        country_codes: 'string',
        country_code: 'string',
        description: 'string',
        life_span: 'string',
        indoor: 0,
        lap: 0,
        adaptability: 0,
        affection_level: 0,
        child_friendly: 0,
        cat_friendly: 0,
        dog_friendly: 0,
        energy_level: 0,
        grooming: 0,
        health_issues: 0,
        intelligence: 0,
        shedding_level: 0,
        social_needs: 0,
        stranger_friendly: 0,
        vocalisation: 0,
        bidability: 0,
        experimental: 0,
        hairless: 0,
        natural: 0,
        rare: 0,
        rex: 0,
        suppressed_tail: 0,
        short_legs: 0,
        wikipedia_url: 'string',
        hypoallergenic: 0,
        reference_image_id: 'abys',
      },
    ],
    id: '1',
    url: 'string',
    width: 0,
    height: 6,
};

export const mockCatDetail: CatDetail = {
  breeds: [
    {
      weight: { imperial: 'string', metric: 'string' },
      id: 'string',
      name: 'string',
      cfa_url: '',
      vetstreet_url: '',
      vcahospitals_url: '',
      temperament: 'string',
      origin: 'string',
      country_codes: 'string',
      country_code: 'string',
      description: 'string',
      life_span: 'string',
      indoor: 0,
      lap: 0,
      adaptability: 0,
      affection_level: 0,
      child_friendly: 0,
      dog_friendly: 0,
      energy_level: 0,
      grooming: 0,
      health_issues: 0,
      intelligence: 0,
      shedding_level: 0,
      social_needs: 0,
      stranger_friendly: 0,
      vocalisation: 0,
      experimental: 0,
      hairless: 0,
      natural: 0,
      rare: 0,
      rex: 0,
      suppressed_tail: 0,
      short_legs: 0,
      wikipedia_url: 'string',
      hypoallergenic: 0,
      reference_image_id: 'abys',
      alt_names: ""
    },
  ],
  id: '1',
  url: 'string',
  width: 0,
  height: 6,
};
